---
- name: Restart CloudWatch Agent
  ansible.builtin.command:
    cmd: >
      /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
      -a fetch-config
      -m ec2
      -c file:{{ cloudwatch_agent_config_path }}
      -s
  changed_when: true
